### ISSUE TITLE
/checkcookie 并非实时检测

### ISSUE THREAD

**Issue by mjyhj** [chiupam/JD_Diy#1]
手动修改成过的让其过期，检测还是正常。需要/restart后才能检测出过期。
同理过期后更新扫码恢复，也不能检测。还是要/restart

**Comment by chiupam** [comment]
表示我目前的版本没有发现这个问题 你可以尝试使用库里新的脚本
新文件的使用方法在这个[README.md](https://github.com/chiupam/JD_Diy/blob/main/jbot/README.md)中提到 如果你有在使用旧的shopbean.py请先删除这个旧的文件再来配置

**Comment by chiupam** [comment]
噢 你说的时延性 我理解了 我起床的时候修复下

**Comment by mjyhj** [comment]
> 噢 你说的时延性 我理解了 我起床的时候修复下
对了，我昨天测试手动修改了一个cookie，另奇失效。现在还原回来，一直给我临时屏蔽了，到现在恢复不了，怎么搞？我12个号，运行的脚本都 提示我提供了11个cookie

**Comment by chiupam** [comment]
我好像找到问题的原因了 可能是因为bot.py开头的这句代码

```py
from ..bot.utils import cookies
```

它应该是在你启动机器人的时候就会读取一次config.sh里面的所有cookie然后存为变量了
但是如果你config.sh里面的cookie更新 机器人不会再次执行这段代码来更新你的cookie 而是一直用旧的变量

**Comment by mjyhj** [comment]
> 我好像找到问题的原因了 可能是因为bot.py开头的这句代码
> 
> ```python
> from ..bot.utils import cookies
> ```
> 
> 它应该是在你启动机器人的时候就会读取一次config.sh里面的所有cookie然后存为变量了
> 但是如果你config.sh里面的cookie更新 机器人不会再次执行这段代码来更新你的cookie 而是一直用旧的变量

我现在这个cookie12，怎么都运行不了脚本。怎么恢复啊，一直被屏蔽了

**Comment by chiupam** [comment]
这个版本的 bot.py 应该修复这个问题了
[修改记录](https://github.com/chiupam/JD_Diy/commit/fb8107e96cef8a1616b05eb297baae2f07a6bbd5)
[bot.py](https://github.com/chiupam/JD_Diy/blob/main/jbot/bot.py)

**Comment by mjyhj** [comment]
现在不用重启机器人，手动删改一次。检测正常了，但是不能恢复屏蔽，显示无需临时屏蔽。实际还是屏蔽了
/checkcookie
以下是屏蔽的账号
12

/checkcookie
没有 Cookie 过期，无需临时屏蔽
