### ISSUE TITLE
求助，在机器人里升级bot.py后，只剩下原始的命令了。

### ISSUE THREAD

**Issue by jaydiao521** [chiupam/JD_Diy#10]

**Comment by chiupam** [comment]
嗯。。。可能你的原机器人没有升级吧
[原机器人的项目仓库](https://github.com/SuMaiKaDe/bot)

**Comment by jaydiao521** [comment]
> 嗯。。。可能你的原机器人没有升级吧
> [原机器人的项目仓库](https://github.com/SuMaiKaDe/bot)

哭了，重新安装bot后彻底失联了 看来要重装了

**Comment by qiuzhongqiang** [comment]
我的也是这个情况。

**Comment by chiupam** [comment]
啊咧 你们可能要升级原机器人才行呢
