### ISSUE TITLE
消息重复

### ISSUE THREAD

**Issue by PJUNYE2** [chiupam/JD_Diy#11]
/list 和 /install /uninstall会重复发两次

**Comment by chiupam** [comment]
笑死 我从昨天中午就发现了 我一直在测试是哪个文件的原因 你等等吧

**Comment by chiupam** [comment]
应该修复了 你试试吧

**Comment by qiuzhongqiang** [comment]
大佬，每次用你电报频道上的/cmd rm -rf diybot.sh && wget https://ghproxy.com/https://raw.githubusercontent.com/chiupam/JD_Diy/master/config/diybot.sh && bash diybot.sh命令，输入到机器人，机器人就恢复到原始功能，用不了你的额外功能。是不是我哪里做错了？求解。谢谢你！！

**Comment by PJUNYE2** [comment]
> 应该修复了 你试试吧

修好了 谢谢
