### ISSUE TITLE
我只要用那个activId.py功能，但是我是否必须装bot？

### ISSUE THREAD

**Issue by hdstar2009** [chiupam/JD_Diy#15]
必须装bot，必须申请tg bot token之类的，国内机器，不想弄bot，
不能直接python3 activeid.py 显示taunActiveId？

**Comment by chiupam** [comment]
不需要 我改一下代码即可

**Comment by chiupam** [comment]
现在应该可以了 检测你有没有bot.json文件 如果没有则直接跳过发送执行结果 你可以用python3 activeId.py来看执行过程和结果

**Comment by hdstar2009** [comment]
谢谢，可以用了。
