### ISSUE TITLE
version 0.9.9.6启动问候语还是又频道消息

### ISSUE THREAD

**Issue by leiletter** [chiupam/JD_Diy#17]
更新（2021-06-22）

移除 /jbot/bot.py ，因需要拆解成单个文件而被移除。
修改 /jbot/upbot.py ，修复因不使用加速代理功能而无法更新的错误，选择更新全部时可能会发送两次问候语，属于正常现象。
新增 /jbot/start.py ，由 bot.py 拆解 /start 的功能而来，发送欢迎语，不在欢迎语中显示频道等消息。
新增 /jbot/restart.py ，由 bot.py 拆解 /restart 的功能而来，重启程序。
新增 /jbot/help.py ，由 bot.py 拆解 /help 的功能而来，发送帮助指令。
新增 /jbot/list.py ，由 bot.py 拆解 /list 的功能而来，查看程序已拓展的功能。
新增 /jbot/install.py ，由 bot.py 拆解 /install 的功能而来，拓展程序功能，拓展成功后不重启程序。
新增 /jbot/uninstall.py ，由 bot.py 拆解 /uninstall 的功能而来，删除程序功能，删除成功后不重启程序。
新增 /jbot/utils.py ，由 bot.py 拆解而来，主要给别的程序调用。
修改 /jbot/user.py ，取消监控此频道，从而取消对 bot.py 和 user.py 文件进行的自动更新替换。
新增 /backup/2021-06-22 目录，备份今天更新之前的所有 jbot 目录文件，已备回滚。
修改 /config/diybot.sh ，可直接升级原机器人和部署自定义机器人，自动判断是否部署 user 和是否存在 diybotset.json 进行特定操作，自动覆盖操作 /jbot/__main__.py 从而修改启动问候语，执行后会发送两次问候语，属于正常现象，请勿提问。
新增 /config/__main__.py ，用于修改启动问候语。

升级请使用 /upbot 指令，选择更新全部。

因为更新比较多的文件，如果使用有问题，请提出 issues，但目前有些功能暂不兼容新青龙！后续修改！
没有进群的请等下轮吧。

实际上问候语甚至多了一行

叮咚，我已成功启动，欢迎使用
原机器人 --> 项目地址  |  交流频道 
diy机器人 --> 项目地址  |  通知频道

**Comment by chiupam** [comment]
新增 /jbot/start.py ，由 bot.py 拆解 /start 的功能而来，发送欢迎语，不在欢迎语中显示频道等消息。
修改 /config/diybot.sh ，可直接升级原机器人和部署自定义机器人，自动判断是否部署 user 和是否存在 diybotset.json 进行特定操作，自动覆盖操作 /jbot/main.py 从而修改启动问候语，执行后会发送两次问候语，属于正常现象，请勿提问。
建议仔细阅读。

**Comment by leiletter** [comment]
谢谢
