### ISSUE TITLE
老大，请教个问题

### ISSUE THREAD

**Issue by donggua1118** [chiupam/JD_Diy#19]
很是喜欢老大bot，之前用v4，很好用，但是换到青龙2.8，发现拓展功能得检测账号过期无法使用，就是checkcookie这个命令，在青龙无法使用吗？

**Comment by chiupam** [comment]
是的 最近期末考试 没空去更新这个功能 而且checkcookie要重做

**Comment by donggua1118** [comment]
感谢老大，好好考试，加油加油💪

**Comment by chiupam** [comment]
现在应该支持了 只是支持一个JD_COOKIE写一个cookie的写法
