### ISSUE TITLE
安装后 原bot和diy功能都不能用了

### ISSUE THREAD

**Issue by Heart-Ace** [chiupam/JD_Diy#24]
之前bot正常运行 安装后如下报错 知道这可能不是您bot的问题 但我实在不知道该如何解决了 或者如何卸载该diy 谢谢
telethon.errors.rpcerrorlist.AuthKeyDuplicatedError: The authorization key (session file) was used under two different IP addresses simultaneously, and can no longer be used. Use the same session exclusively, or use different sessions (caused by InvokeWithLayerRequest)
刚完成安装时 原bot   /start还能用   再之后尝试了/upbot 然后就彻底没反应了 所有命令没反应 只在nohup.log和bot.log找到如上报错

**Comment by chiupam** [comment]
'''shell
docker exec -it qinglong bash
rm -f user.session && rm -f bot.session 
ql bot
'''

**Comment by chiupam** [comment]
The authorization key (session file) was used under two different IP addresses simultaneously, and can no longer be used. 
翻译过来就知道原因了 并不是我机器人的问题

**Comment by Heart-Ace** [comment]
谢谢解答
