### ISSUE TITLE
something wrong,I'm sorry 'data'

### ISSUE THREAD

**Issue by Faker888888** [chiupam/JD_Diy#25]
![1626708169(1)](https://user-images.githubusercontent.com/82194718/126185002-65f516fd-e1d5-47a2-908f-8c8d72ac5a5d.png)

**Comment by Faker888888** [comment]
青龙bot

**Comment by chiupam** [comment]
2.8？

**Comment by Faker888888** [comment]
> 2.8？

是的，2.8

**Comment by chiupam** [comment]
https://t.me/chiupam
