### ISSUE TITLE
大佬，救

### ISSUE THREAD

**Issue by taishunanpo** [chiupam/JD_Diy#27]
我原来用的是v4  bot，我在部署到第二步，把user.py下载到/jbot/diy 目录下的时候出错了，现在没有第三步，输入手机号和验证码的步骤，原来的v4bot也不能用了。。请帮忙看看怎么解决，谢谢大佬~
root@jd:/jd $ rm -rf diybot.sh;wget https://ghproxy.com/https://raw.githubusercontent.com/chiupam/JD_Diy/master/config/diybot.sh;bash diybot.sh
--2021-08-07 10:40:46--  https://ghproxy.com/https://raw.githubusercontent.com/chiupam/JD_Diy/master/config/diybot.sh
Resolving ghproxy.com... 140.238.28.148
Connecting to ghproxy.com|140.238.28.148|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4284 (4.2K) [text/plain]
Saving to: 'diybot.sh'

diybot.sh                        100%[=======================================================>]   4.18K  --.-KB/s    in 0s      

2021-08-07 10:40:48 (393 MB/s) - 'diybot.sh' saved [4284/4284]

更新 bot 所需文件
开始更新仓库 https://github.com/SuMaiKaDe/bot.git 到 /jd/repo/dockerbot
Fetching origin
HEAD is now at cce4f1f Update help.py
Already up to date.
更新 diybot 所需文件
开始更新仓库 https://github.com/chiupam/JD_Diy.git 到 /jd/repo/diybot
Fetching origin
HEAD is now at 036be99 修复启用账号时青龙2.2和2.8的api错误
Already up to date.
检测 /jd/log/bot 目录
  └—结果：存在，跳过
检测 bot 依赖
  └—结果：已安装
修改启动语文件
  └—结果：修改成功
检测 botset.json 文件 
  └—结果：不存在，拉取
cp: cannot stat '/jd/repo/dockerbot/config/botset.json': No such file or directory
检测 diybotset.json 文件 
  └—结果：存在，不拉取
检测 user.py 文件 
  └—结果：存在，默认不更新
检测 diy.py 文件 
  └—结果：存在，不拉取
拉取原机器人文件进入 /jd 目录
拉取diy机器人文件进入 /jd/jbot/diy 目录
grep: /jd/config/botset.json: No such file or directory
[PM2] Applying action restartProcessId on app [jbot](ids: [ 1 ])
[PM2] [jbot](1) ✓
┌─────┬──────────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name                 │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 1   │ jbot                 │ default     │ N/A     │ fork    │ 10256    │ 0s     │ 410  │ online    │ 0%       │ 3.5mb    │ root     │ enabled  │
│ 0   │ jd_crazy_joy_coin    │ default     │ 1.0.0   │ fork    │ 397      │ 40m    │ 0    │ online    │ 0%       │ 60.7mb   │ root     │ enabled  │
└─────┴──────────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
Use --update-env to update environment variables
[PM2] Applying action restartProcessId on app [jbot](ids: [ 1 ])
[PM2] [jbot](1) ✓
┌─────┬──────────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name                 │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 1   │ jbot                 │ default     │ N/A     │ fork    │ 10268    │ 0s     │ 411  │ online    │ 0%       │ 3.9mb    │ root     │ enabled  │
│ 0   │ jd_crazy_joy_coin    │ default     │ 1.0.0   │ fork    │ 397      │ 40m    │ 0    │ online    │ 25.8%    │ 60.7mb   │ root     │ enabled  │
└─────┴──────────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
root@jd:/jd $ cd /jd/jbot/diy;rm -rf user.py;wget https://raw.githubusercontent.com/chiupam/JD_Diy/master/jbot/user.py;cd /jd/;pm2 stop jbot;rm -rf user.session;python3 -m jbot
--2021-08-07 10:41:14--  https://raw.githubusercontent.com/chiupam/JD_Diy/master/jbot/user.py
Resolving raw.githubusercontent.com... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13667 (13K) [text/plain]
Saving to: 'user.py'

user.py                          100%[=======================================================>]  13.35K  --.-KB/s    in 0.001s  

2021-08-07 10:41:14 (19.7 MB/s) - 'user.py' saved [13667/13667]

[PM2] Applying action stopProcessId on app [jbot](ids: [ 1 ])
[PM2] [jbot](1) ✓
┌─────┬──────────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name                 │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 1   │ jbot                 │ default     │ N/A     │ fork    │ 0        │ 0      │ 422  │ stopped   │ 0%       │ 0b       │ root     │ disabled │
│ 0   │ jd_crazy_joy_coin    │ default     │ 1.0.0   │ fork    │ 397      │ 41m    │ 0    │ online    │ 3.6%     │ 60.7mb   │ root     │ enabled  │
└─────┴──────────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/jd/jbot/__main__.py", line 7, in <module>
    from . import jdbot, chat_id, logger, _JdbotDir, _LogDir, _botset, _set, mybot
ImportError: cannot import name '_botset' from 'jbot' (/jd/jbot/__init__.py)

**Comment by chiupam** [comment]
原机器人过旧 先升级原机器人吧
