### ISSUE TITLE
用户发送 raw 链接后自动下载链接文件，“放入*并运行”，v4 cmd命令行拼接错误

### ISSUE THREAD

**Issue by FrogTool** [chiupam/JD_Diy#3]
cmdtext = f'{jdcmd} {_DiyDir} {fname} now'
cmdtext = f'{jdcmd} {_ScriptsDir} {fname} now'

这两处，应该改为

cmdtext = f'{jdcmd} {_DiyDir}/{fname} now'
cmdtext = f'{jdcmd} {_ScriptsDir}/{fname} now'

**Comment by chiupam** [comment]
原来如此 新的版本已经解决了 十分感谢~

**Comment by aenstan** [comment]
> 原来如此 新的版本已经解决了 十分感谢~

能不能.js后缀的文件都可以自动下载保存

**Comment by YamTian** [comment]
不执行吗？

**Comment by chiupam** [comment]
> > 原来如此 新的版本已经解决了 十分感谢~
> 
> 能不能.js后缀的文件都可以自动下载保存

那你不执行吗？

**Comment by aenstan** [comment]
> > > 原来如此 新的版本已经解决了 十分感谢~
> > 
> > 
> > 能不能.js后缀的文件都可以自动下载保存
> 
> 那你不执行吗？

只要raw开头的会自动下载，不是raw开头的，.js结尾的，可以自动下载不？还有.py，.sh能支持不

**Comment by chiupam** [comment]
> > > > 原来如此 新的版本已经解决了 十分感谢~
> > > 
> > > 
> > > 能不能.js后缀的文件都可以自动下载保存
> > 
> > 
> > 那你不执行吗？
> 
> 只要raw开头的会自动下载，不是raw开头的，.js结尾的，可以自动下载不？还有.py，.sh能支持不

现在只要是raw开头的都会下载了呀 但是要你做出选择存储位置 是否需要存储并运行 支持下载任何格式的文件的 不仅限于js 也可以下载py sh

**Comment by aenstan** [comment]
> > > > > 原来如此 新的版本已经解决了 十分感谢~
> > > > 
> > > > 
> > > > 能不能.js后缀的文件都可以自动下载保存
> > > 
> > > 
> > > 那你不执行吗？
> > 
> > 
> > 只要raw开头的会自动下载，不是raw开头的，.js结尾的，可以自动下载不？还有.py，.sh能支持不
> 
> 现在只要是raw开头的都会下载了呀 但是要你做出选择存储位置 是否需要存储并运行 支持下载任何格式的文件的 不仅限于js 也可以下载py sh

我意思不是raw开头的文件下载不了。有些脚本直链不是raw开头

**Comment by chiupam** [comment]
> > > > > > 原来如此 新的版本已经解决了 十分感谢~
> > > > > 
> > > > > 
> > > > > 能不能.js后缀的文件都可以自动下载保存
> > > > 
> > > > 
> > > > 那你不执行吗？
> > > 
> > > 
> > > 只要raw开头的会自动下载，不是raw开头的，.js结尾的，可以自动下载不？还有.py，.sh能支持不
> > 
> > 
> > 现在只要是raw开头的都会下载了呀 但是要你做出选择存储位置 是否需要存储并运行 支持下载任何格式的文件的 不仅限于js 也可以下载py sh
> 
> 我意思不是raw开头的文件下载不了。有些脚本直链不是raw开头

噢噢 你给个例子我改改正则表达式看看

**Comment by aenstan** [comment]
> > > > > > > 原来如此 新的版本已经解决了 十分感谢~
> > > > > > 
> > > > > > 
> > > > > > 能不能.js后缀的文件都可以自动下载保存
> > > > > 
> > > > > 
> > > > > 那你不执行吗？
> > > > 
> > > > 
> > > > 只要raw开头的会自动下载，不是raw开头的，.js结尾的，可以自动下载不？还有.py，.sh能支持不
> > > 
> > > 
> > > 现在只要是raw开头的都会下载了呀 但是要你做出选择存储位置 是否需要存储并运行 支持下载任何格式的文件的 不仅限于js 也可以下载py sh
> > 
> > 
> > 我意思不是raw开头的文件下载不了。有些脚本直链不是raw开头
> 
> 噢噢 你给个例子我改改正则表达式看看

http://mopo-cloud.ddnsfree.com/GitHub/jddockerbot/jbot/ecosystem.config.js
http://mopo-cloud.ddnsfree.com/GitHub/jddockerbot/jbot/utils.py
像这种

**Comment by chiupam** [comment]
> > > > > > > > 原来如此 新的版本已经解决了 十分感谢~
> > > > > > > 
> > > > > > > 
> > > > > > > 能不能.js后缀的文件都可以自动下载保存
> > > > > > 
> > > > > > 
> > > > > > 那你不执行吗？
> > > > > 
> > > > > 
> > > > > 只要raw开头的会自动下载，不是raw开头的，.js结尾的，可以自动下载不？还有.py，.sh能支持不
> > > > 
> > > > 
> > > > 现在只要是raw开头的都会下载了呀 但是要你做出选择存储位置 是否需要存储并运行 支持下载任何格式的文件的 不仅限于js 也可以下载py sh
> > > 
> > > 
> > > 我意思不是raw开头的文件下载不了。有些脚本直链不是raw开头
> > 
> > 
> > 噢噢 你给个例子我改改正则表达式看看
> 
> http://mopo-cloud.ddnsfree.com/GitHub/jddockerbot/jbot/ecosystem.config.js
> http://mopo-cloud.ddnsfree.com/GitHub/jddockerbot/jbot/utils.py
> 像这种

以支持 https://github.com/chiupam/JD_Diy/commit/55f32cd9123b0e1cdd6d2e289574354bfa7debdf
