### ISSUE TITLE
获取的账号数据出问题

### ISSUE THREAD

**Issue by kanjianjiuhao** [chiupam/JD_Diy#30]
![image](https://user-images.githubusercontent.com/24827353/132046467-f570168c-5706-4c1e-ae25-6b191fa589f5.png)

求助怎么修复这个机器人，第一个账号的收支数据也不对，而且目前在挂账号也超过4个
这是之前掉COOKIES后出现的问题，似乎没能刷新回目前的环境变量数值

**Comment by chiupam** [comment]
此功能非自定义机器人的功能 请在这里发起issues

https://github.com/SuMaiKaDe/bot/issues/new

**Comment by kanjianjiuhao** [comment]
> 此功能非自定义机器人的功能 请在这里发起issues
> 
> https://github.com/SuMaiKaDe/bot/issues/new

十分感谢，明白了。祝晚上愉快
