### ISSUE TITLE
不会用

### ISSUE THREAD

**Issue by 810517583** [chiupam/JD_Diy#34]
完全不知道怎么用。就只说了拉去。
"my_chat_id": "-100123456789",
  "zoo_opencard": "False",
  "myzdjr_chatId": "-1001112847619, -1001284907085",
  "myjoinTeam_chatId": "-1001112847619, -1001284907085",
  "shoptokenId": "-1001112847619, -1001284907085",
也没有注释，jbot有个什么token什么的，这个bot没有，我都不知道怎么填写。

**Comment by xlangzhong** [comment]
> 完全不知道怎么用。就只说了拉去。
> "my_chat_id": "-100123456789",
> "zoo_opencard": "False",
> "myzdjr_chatId": "-1001112847619, -1001284907085",
> "myjoinTeam_chatId": "-1001112847619, -1001284907085",
> "shoptokenId": "-1001112847619, -1001284907085",
> 也没有注释，jbot有个什么token什么的，这个bot没有，我都不知道怎么填写。

啊，看不懂就算了

**Comment by 810517583** [comment]
> > 完全不知道怎么用。就只说了拉去。
> > "my_chat_id": "-100123456789",
> > "zoo_opencard": "False",
> > "myzdjr_chatId": "-1001112847619, -1001284907085",
> > "myjoinTeam_chatId": "-1001112847619, -1001284907085",
> > "shoptokenId": "-1001112847619, -1001284907085",
> > 也没有注释，jbot有个什么token什么的，这个bot没有，我都不知道怎么填写。
> 
> 啊，看不懂就算了，你还是别用了

你这个用安装jbot前置吗？还是说你本身就是jbot了

**Comment by xlangzhong** [comment]
@810517583 我是随缘

**Comment by chiupam** [comment]
@xlangzhong 咋就开喷了呢。。。

**Comment by chiupam** [comment]
@810517583 这个不需要修改什么的 你就复制粘贴进去就好了 那些值的话 我后面再给一些提示吧 确实没考虑到这个问题

**Comment by chiupam** [comment]
@810517583 但其实很多频道都不开车了 所以先复制粘贴吧

**Comment by chiupam** [comment]
@810517583 我写了一些提示 你去看看吧 应该可以理解吧

**Comment by xlangzhong** [comment]
@chiupam 哇，活着的大佬

**Comment by 810517583** [comment]
第一个我能理解 后面几个我不懂。不过最主要的原有还是我没有安装前置的jbot。

**Comment by 810517583** [comment]
我已经解决了。

**Comment by Mark2T** [comment]
@xlangzhong 那个是大佬？

**Comment by chiupam** [comment]
@810517583 确实要有原装的机器人作为支撑才能运行的

**Comment by YoYulyvW** [comment]
@Mark2T 楼上

**Comment by utterliar1** [comment]
@810517583 牛逼

**Comment by 810517583** [comment]
> @810517583 确实要有原装的机器人作为支撑才能运行的

wskey_ptkey.py 这个文件没有了吗？仓库找不到，整个git也没有

**Comment by chiupam** [comment]
@810517583 这个只是我自己用的文件 所以不公开

**Comment by xlangzhong** [comment]
> @810517583 这个只是我自己用的文件 所以不公开

看看我，你麻痹我tg被禁言了我发的东西你们都看不到，我能看到你们的消息呜呜呜呜呜呜

**Comment by xlangzhong** [comment]
> @810517583 这个只是我自己用的文件 所以不公开

我发的消息永远只有一个勾勾= =，妈的比我找机器人都不行，我真服了，估计是api调用太多被限制了

**Comment by xlangzhong** [comment]
三老师这个情况怎么解决啊我透不会号没了吧

> @810517583 这个只是我自己用的文件 所以不公开

**Comment by YoYulyvW** [comment]
@xlangzhong 半个小时后见，问题不大，别慌

**Comment by 810517583** [comment]
> @810517583 这个只是我自己用的文件 所以不公开

我在想是不是只要把list转换成数组就可以

**Comment by xlangzhong** [comment]
> @xlangzhong 半个小时后见，问题不大，别慌

好的我先去吃个饭压压惊

**Comment by xlangzhong** [comment]
> @xlangzhong 半个小时后见，问题不大，别慌

建议跟我一样用github来聊天

**Comment by utterliar1** [comment]
我也发不出来消息了，草

**Comment by utterliar1** [comment]
只能看到你们聊天

**Comment by xlangzhong** [comment]
> 只能看到你们聊天

难兄难弟

**Comment by YoYulyvW** [comment]
@utterliar1 等半个钟就好了，吃饭去吧

**Comment by xlangzhong** [comment]
呱佬别管他他就是脑瘫

**Comment by utterliar1** [comment]
好的，监控倒是在跑

**Comment by ZENG61** [comment]
刷的应该都被封了

**Comment by utterliar1** [comment]
哈哈哈，这个好

**Comment by xlangzhong** [comment]
笑死我了一堆人被ban

**Comment by Mark2T** [comment]
我没了。兄弟们下次用小号冲吧

**Comment by utterliar1** [comment]
一看三老师就经常进去，老油子了

**Comment by ZENG61** [comment]
一头牛yyds

**Comment by YoYulyvW** [comment]
@utterliar1 不造谣不信谣不传谣

**Comment by Mark2T** [comment]
还好今天绑定了这个，所以还可以再群内聊天。

**Comment by utterliar1** [comment]
> 还好今天绑定了这个，所以还可以再群内聊天。

-re

**Comment by Mark2T** [comment]
被捉住了，承认错误，下次还敢。

**Comment by Mark2T** [comment]
支持加密！

**Comment by utterliar1** [comment]
@xlangzhong 我发不出来消息了

**Comment by xlangzhong** [comment]
@utterliar1 哈哈哈哈哈哈哈再等一会儿

**Comment by Mark2T** [comment]
跟我一样等吧 大概半小时

**Comment by YoYulyvW** [comment]
发🐔儿，我又被🈲了，发不了了

**Comment by YoYulyvW** [comment]
人在家中坐，锅从天上来，吃完饭再发吧

**Comment by xlangzhong** [comment]
@YoYulyvW 真悲惨

**Comment by YoYulyvW** [comment]
哈哈哈，没事，还好不是发完才🈲，不然都抽不了

**Comment by 2889248467** [comment]
@utterliar1 发不了言了

**Comment by 2889248467** [comment]
@xlangzhong ban了

**Comment by YoYulyvW** [comment]
加密加密，助力没什么，主要是太恶心人

**Comment by 2889248467** [comment]
@2889248467 活了
