### ISSUE TITLE
问题求助

### ISSUE THREAD

**Issue by xyh977732241** [chiupam/JD_Diy#35]
![image](https://user-images.githubusercontent.com/50571734/132191768-7cea43e7-bc47-4663-8c57-4c6e917d2911.png)

**Comment by chiupam** [comment]
@xyh977732241 像是diybotset.json的问题 检查下格式

**Comment by xyh977732241** [comment]
可以了大佬，谢谢..没看到之前的帖子，以为diybotset.json里的第一行是自己的机器人id...改回来就可以了

**Comment by chiupam** [comment]
不是 第一行是自己的测试频道 我最新的模板写了一些提示
