### ISSUE TITLE
执行checkcookie，停不下来了

### ISSUE THREAD

**Issue by QCEnjoyLL** [chiupam/JD_Diy#37]
更新到最新后，执行checkcookie命令好像停不下来了，而且多了好多账号。。
最重要的是，没过期却全部显示过期

![](https://cdn.jsdelivr.net/gh/QCenjoyLL/orange@9a03f61b07036650284a90d501ccf21ad54be509/2021/09/14/3d1dc6fee120b352a935f76c1769d0a2.png)

**Comment by chiupam** [comment]
过段时间我测试下

**Comment by chiupam** [comment]
已修复
