### ISSUE TITLE
自动更新JD_COOKIE环境变量

### ISSUE THREAD

**Issue by Wangsc1** [chiupam/JD_Diy#38]
大佬，为啥cookie失效了没自动更新，已经满足四个条件了（青龙2.8+、环境变量存储wskey、db目录无 wskey.list 文件、有 ql_pandaAPI_refreshCK.py 脚本），难道是我理解错这个自动更新的意思了？😂
![D3A9981F-7AB7-4C67-A536-F88248879D46](https://user-images.githubusercontent.com/26079238/133553266-5a72e389-2673-441c-937a-981f202cbc31.jpeg)

**Comment by YoYulyvW** [comment]
@Wangsc1 你好，是的，你李姐错了

**Comment by Wangsc1** [comment]
> @Wangsc1 你好，是的，你李姐错了

好吧，我以为检测到失效会自动调用ql_pandaAPI_refreshCK.py更新

**Comment by chiupam** [comment]
确实理解有错 收到屏蔽通知只会触发屏蔽操作 不会把wskey转成cookie并替换过期的cookie

**Comment by Wangsc1** [comment]
> 确实理解有错 收到屏蔽通知只会触发屏蔽操作 不会把wskey转成cookie并替换过期的cookie

大佬，后续有自动更新替换的计划不，这样真的超级方便😏

**Comment by chiupam** [comment]
@Wangsc1 暂无 因为不是所有人都是用wskey转cookie的方式更新cookie 而且现在屏蔽操作也有优化的空间
