### ISSUE TITLE
关注店铺myck未添加_ConfigFile

### ISSUE THREAD

**Issue by douzicao** [chiupam/JD_Diy#7]

**Comment by chiupam** [comment]
啊哈 已经加了 你提的要求也已经加了~ 只需要用最新的user.py就可以了~ 然后会自动下载一个diybotset.json在你的config目录 你按照说明设置一下就好了 按照你的说法应该是把-10012345678改成777000就OK咯

**Comment by douzicao** [comment]
> 啊哈 已经加了 你提的要求也已经加了~ 只需要用最新的user.py就可以了~ 然后会自动下载一个diybotset.json在你的config目录 你按照说明设置一下就好了 按照你的说法应该是把-10012345678改成777000就OK咯

看到了所以划掉了，大佬辛苦了，感谢。
