### ISSUE TITLE
替换最新bot.py，重启仍是旧版本

### ISSUE THREAD

**Issue by woboo110** [chiupam/JD_Diy#8]
已把最新bot.py放入了diy文件夹，青龙可更新成功，但v4仍是旧版本， 如下图，请教大佬可能的原因

![image](https://user-images.githubusercontent.com/68997087/121985298-16d25080-cdc7-11eb-8b7a-411f37c680b0.png)

![image](https://user-images.githubusercontent.com/68997087/121985387-3c5f5a00-cdc7-11eb-9702-8736a3ef6396.png)

**Comment by chiupam** [comment]
可能是diy没有映射出宿主机？可能是你重启机器人失败？

**Comment by woboo110** [comment]
> 可能是diy没有映射出宿主机？可能是你重启机器人失败？

谢谢大佬，重装搞定
