### ISSUE TITLE
老哥最新版本的添加dl 定时任务报错

### ISSUE THREAD

**Issue by prcxu** [chiupam/JD_Diy#9]

**Comment by chiupam** [comment]
嗯。。。其实这个/dl功能不是我机器人的功能 是原机器人的功能 因为我是直接引用了原机器人的方法 所以我是修复不了的 得等原机器人修复 不过现在好像已经修复了 你更新一下原机器人就好
[原机器人项目地址](https://github.com/SuMaiKaDe/bot)

**Comment by prcxu** [comment]
好的谢谢大佬
